name       : plasma-systemmonitor
version    : 5.27.4
release    : 24
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.4/plasma-systemmonitor-5.27.4.tar.xz : 294847847d9ade0cad8723f4af95bf5b36588c43c69ae4e624aaee3c2b45c3eb
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
    - ksystemstats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
