name       : plasma-systemmonitor
version    : 5.27.6
release    : 26
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.6/plasma-systemmonitor-5.27.6.tar.xz : 796eb25f061f05cd4e59019cfe902cb61d53be60904bec69366b347c3cfb9c1d
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
    - ksystemstats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
