name       : plasma-systemmonitor
version    : 5.24.2
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.2/plasma-systemmonitor-5.24.2.tar.xz : 16902047b659cbe7e3452e527699aa8891546323a54efc60d0fdcfac8fe0ccd4
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
    - ksystemstats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
