name       : plasma-systemmonitor
version    : 5.23.5
release    : 14
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/plasma-systemmonitor-5.23.5.tar.xz : 8e8600ea93124c9d14fe245fbcda47daa5d594c4274100c0d43929f9fa52dfea
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
    - ksystemstats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
