name       : plasma-systemmonitor
version    : 5.27.5
release    : 25
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/plasma-systemmonitor-5.27.5.tar.xz : 82e551398f208270f543d5f91be6f3f3b27b1ce9f2c0e90263f29f8d238b2e34
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
    - ksystemstats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
