name       : plasma-systemmonitor
version    : 5.23.3
release    : 12
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.3/plasma-systemmonitor-5.23.3.tar.xz : 17fd59d0cff3c155cea48687cb1e566981d3bcec1f8a1557ea051dde66768fca
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
    - ksystemstats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
