name       : plasma-systemmonitor
version    : 5.22.4
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.4/plasma-systemmonitor-5.22.4.tar.xz : 8b0d43e91d8ba368fed96d63b34aee7f401a9c0cc47533b363bca365a69c86be
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
    - ksystemstats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
