name       : plasma-systemmonitor
version    : 5.21.3
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.21.3/plasma-systemmonitor-5.21.3.tar.xz : 941e7a48d8c68ed072848110764e80e3596aea66a6fb99913301cc7f2bfe3df0
license    : GPL-3.0-only
component  : desktop.kde
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
