name       : plasma-systemmonitor
version    : 5.22.5
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.5/plasma-systemmonitor-5.22.5.tar.xz : dd9eaaeba11da2d9640873882ed4aa573c2b3fc2f5640783965992ceda1647a3
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
    - ksystemstats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
