name       : plasma-systemmonitor
version    : 5.21.5
release    : 3
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.5/plasma-systemmonitor-5.21.5.tar.xz : 3c4d7facd472fd68eee6c7f7175539eeae42bf8a6d6c8e41925a0b0fd6988ecf
license    : GPL-3.0-only
component  : desktop.kde
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
builddeps  :
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - libksysguard-devel
rundeps    :
    - kirigami2
    - qt5-quickcontrols2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
